package swag.events {
	
	import swag.events.SwagEvent;
	import swag.interfaces.events.ISwagErrorEvent;
	/**
	 * Extends the <code>SwagEvent</code> class for broadcasting error messages generated by the <em>SwAG Toolkit</em>. This
	 * class is used to broadcast any errors that are not thrown (i.e. non-fatal code errors). 
	 * 
	 * @author Patrick Bay
	 * 
	 */	
	public class SwagErrorEvent extends SwagEvent implements ISwagErrorEvent {
		
		public static const ERROR:String="swagErrorEvent";
		
		/**
		 * Creates a new <code>SwagErrorEvent</code> instance which can subsequently be broadcast using the standard
		 * Flash event system.
		 *  
		 * @param type The type of event to broadcast. If this parameter is omitted, or is null, or a blank string, a generic
		 * <code>SwagErrorEvent.ERROR</code>-type event will be created. Use the included static properties for other error codes.
		 * @param bubbles Passed as is to the standard Flash Event constructor.
		 * @param cancelable Passed as is to the standard Flash Event constructor.
		 * 
		 * @see flash.events.Event 
		 */		
		public function SwagErrorEvent(type:String=null, bubbles:Boolean=false, cancelable:Boolean=false) {
			if ((type==null) || (type=="")) {
				type=SwagErrorEvent.ERROR;
			}//if
			super(type, bubbles, cancelable);
		}//constructor
		
	}//SwagErrorEvent class
	
}//package